require('dotenv').config();
const path = require('path');
const express = require('express');
const admin = require('firebase-admin');

const required = ['FIREBASE_PROJECT_ID', 'FIREBASE_CLIENT_EMAIL', 'FIREBASE_PRIVATE_KEY', 'FIREBASE_DATABASE_URL', 'FIREBASE_WEB_API_KEY'];
const missing = required.filter((key) => !process.env[key]);
if (missing.length) console.warn(`Firebase ยังไม่ถูกตั้งค่า: ${missing.join(', ')}`);

if (!admin.apps.length && !missing.length) {
  admin.initializeApp({ credential: admin.credential.cert({ projectId: process.env.FIREBASE_PROJECT_ID, clientEmail: process.env.FIREBASE_CLIENT_EMAIL, privateKey: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n') }), databaseURL: process.env.FIREBASE_DATABASE_URL });
}
const app = express(); app.use(express.json()); app.use(express.static(path.join(__dirname, 'public'))); app.use(express.static(__dirname, { index: 'index.html', extensions: ['html'] }));
const configured = () => !missing.length;
const failIfUnconfigured = (res) => { if (!configured()) { res.status(503).json({ message: 'ยังไม่ได้ตั้งค่า Firebase ในไฟล์ .env' }); return true; } };
const usernameKey = (username) => String(username || '').trim().toLowerCase();
const SIGNUP_TIMEOUT_MS = 60_000;
async function removeExpiredPendingAccount(uid) {
  const profile = (await admin.database().ref(`users/${uid}`).get()).val();
  if (!profile || profile.rfidStatus !== 'pending' || !profile.rfidExpiresAt || profile.rfidExpiresAt > Date.now()) return false;
  const updates = { [`users/${uid}`]: null, [`rfidEnrollmentQueue/${uid}`]: null };
  if (profile.username) updates[`usernames/${usernameKey(profile.username)}`] = null;
  await admin.database().ref().update(updates);
  try { await admin.auth().deleteUser(uid); } catch (error) { if (error.code !== 'auth/user-not-found') throw error; }
  return true;
}
function schedulePendingAccountRemoval(uid, expiresAt) {
  setTimeout(() => removeExpiredPendingAccount(uid).catch(console.error), Math.max(0, expiresAt - Date.now()));
}
async function authenticate(req, res, next) { if (failIfUnconfigured(res)) return; try { const token = req.headers.authorization?.replace(/^Bearer\s+/i, ''); req.user = await admin.auth().verifyIdToken(token); next(); } catch { res.status(401).json({ message: 'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่' }); } }
async function ensureProfile(uid) { const ref = admin.database().ref(`users/${uid}`); const snapshot = await ref.get(); if (snapshot.exists()) return snapshot.val(); const user = await admin.auth().getUser(uid); const profile = { username: user.displayName || null, email: user.email || null, rfidStatus: 'unverified', rfidUid: null, createdAt: admin.database.ServerValue.TIMESTAMP }; await ref.set(profile); return profile; }
async function accountData(uid) { const profile = await ensureProfile(uid); const lockers = (await admin.database().ref('lockers').get()).val() || {}; const ownedLockerIds = Object.entries(lockers).filter(([, locker]) => locker?.ownerUid === uid).map(([id]) => Number(id)); return { profile, ownedLockerIds }; }

app.post('/api/login', async (req, res) => { if (failIfUnconfigured(res)) return; const { identifier, password } = req.body; if (!identifier || !password) return res.status(400).json({ message: 'กรอก Username/Email และ Password ให้ครบ' }); try { let email = String(identifier).trim(); if (!email.includes('@')) { const record = await admin.database().ref(`usernames/${usernameKey(email)}`).get(); email = record.val()?.email; } if (!email) return res.status(401).json({ message: 'Username หรือ Password ไม่ถูกต้อง' }); const response = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${process.env.FIREBASE_WEB_API_KEY}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, returnSecureToken: true }) }); const data = await response.json(); if (!response.ok) return res.status(401).json({ message: 'Username/Email หรือ Password ไม่ถูกต้อง' }); const decoded = await admin.auth().verifyIdToken(data.idToken); const profile = await ensureProfile(decoded.uid); res.json({ token: data.idToken, next: profile.rfidStatus === 'pending' ? 'rfid' : 'dashboard' }); } catch { res.status(502).json({ message: 'ไม่สามารถเชื่อมต่อ Firebase Authentication ได้' }); } });
app.post('/api/register', async (req, res) => { if (failIfUnconfigured(res)) return; const { username, email, password } = req.body; const key = usernameKey(username); if (!/^[a-z0-9._-]{3,30}$/.test(key)) return res.status(400).json({ message: 'Username ต้องมี 3–30 ตัว ใช้อักษรอังกฤษ ตัวเลข . _ หรือ -' }); if (!email || !password || password.length < 6) return res.status(400).json({ message: 'กรอกอีเมลและ Password อย่างน้อย 6 ตัวอักษร' }); try { const indexRef = admin.database().ref(`usernames/${key}`); const existing = await indexRef.get(); if (existing.exists()) return res.status(409).json({ message: 'Username นี้ถูกใช้งานแล้ว' }); const user = await admin.auth().createUser({ email: email.trim(), password, displayName: username.trim() }); try { await admin.database().ref().update({ [`users/${user.uid}`]: { username: username.trim(), email: email.trim(), rfidStatus: 'pending', rfidUid: null, createdAt: admin.database.ServerValue.TIMESTAMP }, [`usernames/${key}`]: { uid: user.uid, email: email.trim() }, [`rfidEnrollmentQueue/${user.uid}`]: { requestedAt: admin.database.ServerValue.TIMESTAMP } }); } catch (dbError) { await admin.auth().deleteUser(user.uid); throw dbError; } const response = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${process.env.FIREBASE_WEB_API_KEY}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: email.trim(), password, returnSecureToken: true }) }); const session = await response.json(); if (!response.ok) { const error = new Error(session.error?.message || 'สร้างบัญชีสำเร็จ แต่ไม่สามารถเข้าสู่ระบบอัตโนมัติ'); error.code = session.error?.message; throw error; } res.status(201).json({ token: session.idToken }); } catch (error) { if (error.code === 'auth/email-already-exists') return res.status(409).json({ message: 'Email นี้ถูกใช้งานแล้ว' }); if (error.code === 'CONFIGURATION_NOT_FOUND') return res.status(503).json({ message: 'ยังไม่ได้เปิด Email/Password ใน Firebase Authentication' }); res.status(500).json({ message: error.message || 'สร้างบัญชีไม่สำเร็จ' }); } });
app.get('/api/me', authenticate, async (req, res) => { try { res.json(await accountData(req.user.uid)); } catch { res.status(500).json({ message: 'อ่านข้อมูลบัญชีไม่สำเร็จ' }); } });
app.post('/api/rfid/scan', async (req, res) => { if (!process.env.DEVICE_API_KEY || req.headers['x-device-key'] !== process.env.DEVICE_API_KEY) return res.status(401).json({ message: 'Device key ไม่ถูกต้อง' }); if (failIfUnconfigured(res)) return; const cardUid = String(req.body?.cardUid || '').replace(/[^a-zA-Z0-9_-]/g, '').toUpperCase(); if (cardUid.length < 4) return res.status(400).json({ message: 'RFID card UID ไม่ถูกต้อง' }); try { const occupied = await admin.database().ref(`rfidCards/${cardUid}`).get(); if (occupied.exists()) return res.status(409).json({ message: 'บัตรนี้ถูกยืนยันแล้ว' }); const queue = (await admin.database().ref('rfidEnrollmentQueue').get()).val() || {}; const next = Object.entries(queue).sort(([, a], [, b]) => (a.requestedAt || 0) - (b.requestedAt || 0))[0]; if (!next) return res.status(202).json({ message: 'ไม่มีผู้ใช้รอยืนยัน RFID' }); const [uid] = next; await admin.database().ref().update({ [`users/${uid}/rfidStatus`]: 'verified', [`users/${uid}/rfidUid`]: cardUid, [`rfidCards/${cardUid}`]: { uid, verifiedAt: admin.database.ServerValue.TIMESTAMP }, [`rfidEnrollmentQueue/${uid}`]: null }); res.json({ message: 'ยืนยันบัตร RFID สำเร็จ' }); } catch { res.status(500).json({ message: 'บันทึกบัตร RFID ไม่สำเร็จ' }); } });
app.get('/api/lockers', authenticate, async (req, res) => { try { const value = (await admin.database().ref('lockers').get()).val() || {}; const owned = Object.fromEntries(Object.entries(value).filter(([, locker]) => locker?.ownerUid === req.user.uid)); res.json({ lockers: owned }); } catch { res.status(500).json({ message: 'อ่านข้อมูลล็อกเกอร์ไม่สำเร็จ' }); } });
app.post('/api/lockers/:id', authenticate, async (req, res) => { const id = Number(req.params.id), { action } = req.body; if (![1, 2, 3].includes(id) || !['lock', 'unlock'].includes(action)) return res.status(400).json({ message: 'คำสั่งล็อกเกอร์ไม่ถูกต้อง' }); try { const locker = (await admin.database().ref(`lockers/${id}`).get()).val(); if (!locker || locker.ownerUid !== req.user.uid) return res.status(403).json({ message: 'คุณไม่มีสิทธิ์ควบคุมล็อกเกอร์ช่องนี้' }); const state = action === 'unlock' ? 'open' : 'locked'; const payload = { state, updatedAt: admin.database.ServerValue.TIMESTAMP, updatedBy: req.user.uid }; await admin.database().ref(`lockers/${id}`).update(payload); await admin.database().ref('events').push({ lockerId: id, action, by: req.user.uid, at: admin.database.ServerValue.TIMESTAMP }); const lockers = (await admin.database().ref('lockers').get()).val() || {}; const owned = Object.fromEntries(Object.entries(lockers).filter(([, item]) => item?.ownerUid === req.user.uid)); res.json({ lockers: owned }); } catch { res.status(500).json({ message: 'บันทึกคำสั่งลง Firebase ไม่สำเร็จ' }); } });
app.listen(process.env.PORT || 3000, () => console.log(`Smart Locker: http://localhost:${process.env.PORT || 3000}`));
